version: '3.8'
services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: user-password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_server:/var/lib/mysql
    
